### ISSUE TITLE
type identification

### ISSUE THREAD

**Issue by micah-at-talos** [christophschlosser/doxdocgen#31] opened 2017-11-22 17:01 UTC
As a vscode enthusiast with a definite need to improve documentation in projects that I work on, I decided to try out doxdocgen.  I started by completely randomly selecting this line to test my first function comment block:
https://github.com/vrtadmin/clamav-devel/blob/master/libclamav/htmlnorm.c#L158

Return type should have been unsigned int, as both return statements in the function return variables of type unsigned int.  

The function parameters identified as char instead of chunk, and int instead of len.  

Finally I also found that the function name appeared at the end of the @return line instead of at the beginning of the block. 

```C
/**
 * @brief 
 * 
 * @param char 
 * @param int 
 * @return unsigned rewind_tospace 
 */
static inline unsigned int rewind_tospace(const unsigned char* chunk, unsigned int len)
```

**Comment by christophschlosser** [comment] 2017-11-22 18:32
Sorry for making such a terrible first impression ;)

Something is really wrong here. I will take a look at it, thanks for sharing!

**Comment by micah-at-talos** [comment] 2017-11-22 18:34
No worries!  I'll continue to use your plugin regardless.  I look forward to future improvements.  I wish I had time to chip in with the project.

**Comment by rowanG077** [comment] 2017-11-22 18:35
The issue is in CParser. Currently there is no special case for the fundemental types. I overlooked them. Most easy way to fix it is to build in a special case for the symbol vocabulary lambda.

All special cases are lasted here: http://en.cppreference.com/w/cpp/language/types

**Comment by christophschlosser** [comment] 2017-11-22 20:29
I think it is somewhere in this piece.
Not quite sure yet how to fix this but I'll probably take another look at it tomorrow or the following days.

```Typescript
private GetDefaultArgument(tree: ParseTree, isRetVal: boolean): Argument {
        ...
            const symbolCount = argument.Type.nodes
                .filter((n) => n instanceof Token)
                .map((n) => n as Token)
                .filter((n) => n.Type === TokenType.Symbol)
                .filter((n) => this.keywords.find((k) => k === n.Value) === undefined)
                .length;

            if (node.Type === TokenType.Symbol
                && this.keywords.find((k) => k === node.Value) === undefined) {
                if (symbolCount === 1) {
                    argument.Name += node.Value;
                    continue;
                } else if (symbolCount > 1) {
                    throw new Error("Too many non keyword symbols.");
                }
            }
            argument.Type.nodes.push(node);
        }
```

**Comment by rowanG077** [comment] 2017-11-23 18:51
@christophschlosser Do you plan on working on it? If not I can take a look this weekend because this is a pretty glaring bug.

**Comment by rowanG077** [comment] 2017-11-23 19:39
Actually it was rather easy to fix once I thought of a good method. I actually could delete some more special case code afterwards.

See pull request: https://github.com/christophschlosser/doxdocgen/pull/32

**Comment by christophschlosser** [comment] 2017-11-23 20:58
Thanks @rowanG077 again!

@micah-at-talos I'll close this issue. If you find another bug or have any questions please open another one!

**Closed by christophschlosser** 2017-11-23 20:58 UTC
Labels: bug

**Comment by micah-at-talos** [comment] 2017-11-23 21:38
That's awesome, and fast!  I'll be sure to open new issues if I find any.  Thanks!

**Comment by christophschlosser** [comment] 2018-02-22 10:25
Hey @micah-at-talos :)

Had you time to check out the new version of the plugin? It should improve comment generation a lot, thanks to great contributions from @rowanG077.

If you like the plugin now more then initially maybe you could consider changing your rating on the VS marketplace ;)

**Comment by r12f** [comment] 2019-05-12 20:18
Hi @christophschlosser , I am still seeing this issue. Our code is using SAL annotations, which looks like the following. And the parameter will still shows the (part of) type instead of the name.
```
class Foo
{
    /**
     * @brief 
     * 
     * @param int 
     * @param char 
     */
    void Bar(_In_ int* a, _In_ char* b);
};
```

**Comment by christophschlosser** [comment] 2019-05-14 19:34
Hi @r12f , this is a Microsoft thing right?

If this is not in the standard C/C++ please open a different issue.

**Comment by tandasat** [comment] 2020-04-21 02:12
Hi @christophschlosser @r12f , is there an issue about this annotation thing? If not, I will file a ticket. 

This is not necessarily a Microsoft thing, for example, EDK2 (UEFI) coding standard requires something similar to be used. I will elaborate more on an appropriate ticket.

**Comment by christophschlosser** [comment] 2020-04-26 10:55
Hi @tandasat ,

IIRC @r12f never opened a different issue so feel free to do so.
